[build]
  publish = "public"          # Directorio donde están tus archivos HTML/CSS/JS
  functions = ".netlify/functions" # Directorio donde están tus funciones Lambda de Python

[functions]
  python_version = "3.9"      # O la versión de Python que prefieras (ej. "3.10", "3.11")
  external_packages = [ "requests" ] # Indicar las librerías externas que necesita tu función Python
  # Puedes añadir esto para depuración si la función no responde:
  # NETLIFY_PYTHON_LOG_LEVEL = "DEBUG"
