[build]
  publish = "public"
  functions = ".netlify/functions"

[functions]
  # Esta es la nueva forma correcta para dependencias Python
  python_packages = [ "requests" ]

  # Elimina cualquier otra línea relacionada con external_packages o external_node_modules
  # NETLIFY_PYTHON_LOG_LEVEL = "DEBUG" # Puedes mantener esto o borrarlo
