[build]
  publish = "public"
  functions = ".netlify/functions"

# Elimina completamente la sección [functions] de aquí.
# Netlify detectará el requirements.txt en .netlify/functions automáticamente.
